
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- LÍNEA DE IMÁGENES: CUIDADO FACIAL REAFIRMANTE ---
    {
        id: 22424,
        name: "Crema de Día Reafirmante Royal Velvet SPF 20",
        brand: "Royal Velvet",
        price: 18.99,
        regularPrice: 32.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F22424%2F22424_1.png',
        description: "Enriquecida con la exclusiva Infusión de Iris Negro, esta crema fortalece la estructura de la piel madura, restaura su firmeza y reduce visiblemente las arrugas mientras protege con SPF 20. Una joya de estilismo facial.",
        stock: 95,
        category: 'skincare',
        tag: 'OFERTA',
        rating: 4.9,
        reviewCount: 3200,
    },
    {
        id: 22814,
        name: "Crema de Noche Reafirmante Royal Velvet",
        brand: "Royal Velvet",
        price: 18.99,
        regularPrice: 32.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F22814%2F22814_1.png',
        description: "Tratamiento nocturno intensivo que restaura la elasticidad natural. Su fórmula con Iris Negro trabaja durante el ciclo de descanso para despertar con una piel visiblemente más densa y suave.",
        stock: 70,
        category: 'skincare',
        tag: 'SET',
        rating: 5,
        reviewCount: 2850,
    },
    {
        id: 13659,
        name: "Crema Anti-Envejecimiento Diamond Cellular",
        brand: "Diamond Cellular",
        price: 29.99,
        regularPrice: 48.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F13659%2F13659_1.png',
        description: "Lujo supremo con auténtico Polvo de Diamante. Esta crema 'todo en uno' actúa a nivel celular para iluminar el cutis, reducir arrugas y unificar el tono. El Diamond Elixir™ aporta una luminosidad estelar.",
        stock: 40,
        category: 'skincare',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 1100,
    },

    // --- LÍNEA DE IMÁGENES: MAQUILLAJE & HIGIENE ---
    {
        id: 43242,
        name: "Base Giordani Gold Eternal Glow SPF 25",
        brand: "Giordani Gold",
        price: 22.99,
        regularPrice: 36.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43242%2F43242_1.png',
        description: "Base híbrida con 90% de tratamiento. Infundida con Ácido Hialurónico y Niacinamida para un acabado luminoso eterno. Cobertura modulable con tacto de seda para un estilismo de maquillaje profesional.",
        stock: 85,
        category: 'makeup',
        tag: 'NOVEDAD',
        rating: 4.9,
        reviewCount: 1205,
    },
    {
        id: 43925,
        name: "Activelle Invisible Fresh 48h",
        brand: "Activelle",
        price: 4.49,
        regularPrice: 9.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43925%2F43925_1.png',
        description: "Antitranspirante de alta tecnología. La tecnología ActiBoost libera frescura con el movimiento. Fórmula invisible que protege tus prendas favoritas de manchas blancas.",
        stock: 200,
        category: 'personal-care',
        tag: 'OFERTA',
    },

    // --- PRODUCTOS DESDE CSV (OFERTAS 2026) ---
    {
        id: 48028,
        name: "Eau de Parfum Giordani Gold White",
        brand: "Giordani Gold",
        price: 22.32,
        regularPrice: 42.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48028%2F48028_1.png',
        description: "Una fragancia luminosa y sofisticada que captura la esencia de la elegancia italiana con notas de azahar y pachulí. Presentada en un frasco de diseño clásico 2026.",
        stock: 45,
        category: 'perfume',
        tag: 'OFERTA',
    },
    {
        id: 46801,
        name: "Eau de Parfum Divine Dark Velvet",
        brand: "Oriflame Fragrances",
        price: 34.65,
        regularPrice: 55.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png',
        description: "Intenso, glamuroso y aterciopelado. Una fragancia floral oriental diseñada para la mujer que desea destacar en la noche. Notas profundas y estela duradera.",
        stock: 28,
        category: 'perfume',
        tag: 'OFERTA',
    },
    {
        id: 47697,
        name: "Champú Nutritivo Milk & Honey Gold",
        brand: "Milk & Honey",
        price: 6.99,
        regularPrice: 12.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47697%2F47697_1.png',
        description: "Limpia y nutre profundamente el cabello dejándolo suave y brillante. Con extractos orgánicos de leche y miel que cuidan tu fibra capilar.",
        stock: 300,
        category: 'hair',
        tag: 'OFERTA',
    },
    {
        id: 47536,
        name: "Crema Manos/Cuerpo Majestic Magnolia",
        brand: "Milk & Honey",
        price: 11.99,
        regularPrice: 18.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47536%2F47536_1.png',
        description: "Edición limitada de lujo. Nutrición clásica de Milk & Honey fusionada con el aroma floral real de la Magnolia. Deja la piel suave y delicadamente perfumada.",
        stock: 635,
        category: 'personal-care',
        tag: 'SET',
    },
    {
        id: 40672,
        name: "Máscara 5 en 1 Wonder Lash XXL",
        brand: "THE ONE",
        price: 7.49,
        regularPrice: 16.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F40672%2F40672_1.png',
        description: "Pestañas con volumen masivo y definición pelo a pelo. El bestseller mundial de Oriflame ahora en oferta especial 2026. Longitud extrema y rizo instantáneo.",
        stock: 1550,
        category: 'makeup',
        tag: 'OFERTA',
    },
    {
        id: 48573,
        name: "Rizador de Pestañas Magical Midnights",
        brand: "Oriflame Tools",
        price: 3.49,
        regularPrice: 8.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48573%2F48573_1.png',
        description: "Curvatura profesional sin tirones. Diseño ergonómico de edición limitada con acabado premium. Imprescindible para tu neceser de estilismo.",
        stock: 13,
        category: 'accessories',
        tag: 'OFERTA',
    },
    {
        id: 46134,
        name: "BB Cream Beautifier MAX SPF 15",
        brand: "THE ONE",
        price: 7.99,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46134%2F46134_1.png',
        description: "Hidratación, color y protección en un solo paso. Perfecciona el rostro al instante con un acabado ultra natural y ligero. Protección solar integrada.",
        stock: 289,
        category: 'makeup',
        tag: 'OFERTA',
    },
    {
        id: 42444,
        name: "Power Drops 10% Niacinamide NovAge+",
        brand: "NovAge+",
        price: 24.99,
        regularPrice: 38.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42444%2F42444_1.png',
        description: "Sérum ultra concentrado que perfecciona la textura. Reduce poros, manchas e imperfecciones con Niacinamida pura. Resultados visibles en 7 días.",
        stock: 55,
        category: 'skincare',
        tag: 'NOVEDAD',
    },
    {
        id: 44952,
        name: "Pasta de Dientes Máxima Frescura Optifresh",
        brand: "Optifresh",
        price: 7.70,
        regularPrice: 10.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44952%2F44952_1.png',
        description: "Frescura intensa que dura horas. Protección anticaries completa y tecnología Pro-White para una sonrisa más luminosa y saludable.",
        stock: 500,
        category: 'personal-care',
    },
    {
        id: 99001,
        name: "Bolsa de Oferta VIP Oriflame 2026",
        brand: "Vellaperfumeria Exclusives",
        price: 45.00,
        regularPrice: 75.00,
        imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=800',
        description: "Nuestra selección sorpresa anual. Contiene 5 productos estrella de 2026 incluyendo maquillaje, cuidado facial y fragancia. El regalo más vendido.",
        stock: 50,
        category: 'accessories',
        tag: 'SET',
        rating: 5,
        reviewCount: 450,
    }
];
