
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- MAQUILLAJE ORIFLAME 2026 ---
    {
        id: 43242,
        name: "Base de Maquillaje Giordani Gold Eternal Glow SPF 25",
        brand: "Giordani Gold",
        price: 22.99,
        regularPrice: 36.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43242%2F43242_1.png',
        description: "Lujo líquido con 90% de ingredientes de tratamiento facial. Esta base híbrida combina Ácido Hialurónico y Niacinamida para un acabado luminoso eterno. Su aplicador de gotero garantiza una precisión profesional para un estilismo impecable.",
        stock: 85,
        category: 'makeup',
        tag: 'NOVEDAD',
        rating: 4.9,
        reviewCount: 1205,
    },
    {
        id: 42120,
        name: "Máscara de Pestañas THE ONE 5-in-1 Wonder Lash Ultra",
        brand: "THE ONE",
        price: 8.99,
        regularPrice: 16.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42120%2F42120_1.png',
        description: "Impacto Ultra HD en tus pestañas. Volumen, longitud, definición, rizo y cuidado en un solo producto. El cepillo tecnológico captura cada pestaña envolviéndola en pigmentos negros azabache para una mirada épica.",
        stock: 500,
        category: 'makeup',
        tag: 'OFERTA',
        rating: 5,
        reviewCount: 15420,
    },
    {
        id: 42484,
        name: "Brocha para Colorete e Iluminador Blush & Glow",
        brand: "Oriflame Tools",
        price: 7.49,
        regularPrice: 14.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42484%2F42484_1.png',
        description: "Cerdas ultrasuaves de corte angular diseñadas para esculpir el rostro con precisión. Ideal para aplicar colorete o iluminador con transiciones de color naturales.",
        stock: 120,
        category: 'makeup',
        tag: 'OFERTA',
        rating: 4.8,
        reviewCount: 450,
    },

    // --- CUIDADO FACIAL AVANZADO ---
    {
        id: 22424,
        name: "Crema de Día Reafirmante Royal Velvet SPF 20",
        brand: "Royal Velvet",
        price: 18.99,
        regularPrice: 32.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F22424%2F22424_1.png',
        description: "Enriquecida con la exclusiva Infusión de Iris Negro. Esta crema fortalece la piel madura, restaura su firmeza y reduce visiblemente las arrugas mientras protege con SPF 20.",
        stock: 95,
        category: 'skincare',
        tag: 'OFERTA',
        rating: 4.9,
        reviewCount: 3200,
    },
    {
        id: 22814,
        name: "Crema de Noche Reafirmante Royal Velvet",
        brand: "Royal Velvet",
        price: 18.99,
        regularPrice: 32.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F22814%2F22814_1.png',
        description: "Tratamiento nocturno intensivo que restaura la elasticidad natural de la piel. Su textura rica y fundente trabaja mientras duermes para un despertar con rostro rejuvenecido.",
        stock: 70,
        category: 'skincare',
        tag: 'SET',
        rating: 5,
        reviewCount: 2850,
    },
    {
        id: 13659,
        name: "Crema Anti-Envejecimiento Diamond Cellular",
        brand: "Diamond Cellular",
        price: 29.99,
        regularPrice: 48.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F13659%2F13659_1.png',
        description: "Lujo supremo con auténtico Polvo de Diamante. Actúa a nivel celular para iluminar, reducir arrugas y unificar el tono. El Diamond Elixir™ acelera la renovación celular.",
        stock: 40,
        category: 'skincare',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 1100,
    },
    {
        id: 42444,
        name: "NovAge+ Proceuticals 10% Niacinamide Power Drops",
        brand: "NovAge+",
        price: 24.99,
        regularPrice: 38.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42444%2F42444_1.png',
        description: "Tratamiento concentrado para perfeccionar la textura. Reduce poros, manchas e imperfecciones drásticamente con Niacinamida pura al 10%.",
        stock: 55,
        category: 'skincare',
        tag: 'NOVEDAD',
        rating: 4.9,
        reviewCount: 620,
    },
    {
        id: 41033,
        name: "NovAge+ Restore Renewing Eye & Lip Contour Cream",
        brand: "NovAge+",
        price: 19.99,
        regularPrice: 32.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F41033%2F41033_1.png',
        description: "Contorno dual para ojos y labios. Combate flacidez y arrugas profundas con tecnología Bio-Boost. Restaura la juventud en las zonas más delicadas.",
        stock: 80,
        category: 'skincare',
        tag: 'OFERTA',
        rating: 4.8,
        reviewCount: 340,
    },

    // --- FRAGANCIAS Y CUIDADO PERSONAL ---
    {
        id: 38497,
        name: "Divine Eau de Parfum - Classic Blue",
        brand: "Oriflame Fragrances",
        price: 26.99,
        regularPrice: 44.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38497%2F38497_1.png',
        description: "Elegancia floral atemporal con notas de Orquídea y Lirio. Un icono de la sofisticación femenina en un frasco de diseño escultórico.",
        stock: 65,
        category: 'perfume',
        tag: 'OFERTA',
        rating: 4.9,
        reviewCount: 2300,
    },
    {
        id: 38498,
        name: "Divine Exclusive Eau de Parfum - Luxury Black",
        brand: "Oriflame Fragrances",
        price: 32.99,
        regularPrice: 52.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38498%2F38498_1.png',
        description: "La máxima expresión del lujo con el acorde 'Shining Star'. Frasco negro mate con detalles dorados para noches de gala inolvidables.",
        stock: 30,
        category: 'perfume',
        tag: 'SET',
        rating: 5,
        reviewCount: 890,
    },
    {
        id: 43925,
        name: "Activelle Invisible Fresh 48h Anti-perspirant",
        brand: "Activelle",
        price: 4.49,
        regularPrice: 9.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43925%2F43925_1.png',
        description: "Protección invisible 48h con tecnología ActiBoost. No deja manchas blancas y libera frescura con el movimiento.",
        stock: 200,
        category: 'personal-care',
        tag: 'OFERTA',
        rating: 4.7,
        reviewCount: 12400,
    },
    {
        id: 33142,
        name: "Activelle Extreme 72h Anti-perspirant",
        brand: "Activelle",
        price: 4.49,
        regularPrice: 9.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F33142%2F33142_1.png',
        description: "Máxima seguridad para situaciones extremas. Protección de 72 horas con aroma limpio y refrescante.",
        stock: 180,
        category: 'personal-care',
        tag: 'OFERTA',
        rating: 4.8,
        reviewCount: 9800,
    },
    {
        id: 44956,
        name: "Champú Duologi Colour Protect",
        brand: "Duologi",
        price: 9.99,
        regularPrice: 16.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F44956%2F44956_1.png',
        description: "Escudo protector para cabellos teñidos. Con Vitamina E y Granada para sellar el color y aportar brillo extremo.",
        stock: 140,
        category: 'hair',
        tag: 'OFERTA',
        rating: 4.8,
        reviewCount: 780,
    },

    // --- SETS DE REGALO Y OFERTAS ORO ---
    {
        id: 99001,
        name: "Bolsa de Oferta VIP Oriflame 2026",
        brand: "Vellaperfumeria Exclusives",
        price: 45.00,
        regularPrice: 75.00,
        imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=800',
        description: "El regalo definitivo. Elegante bolsa de diseño que incluye 5 productos estrella Oriflame 2026. Ahorro directo del 40%.",
        stock: 50,
        category: 'accessories',
        tag: 'SET',
        rating: 5,
        reviewCount: 450,
    },
    {
        id: 99002,
        name: "Caja de Regalo Milk & Honey Gold",
        brand: "Milk & Honey",
        price: 29.99,
        regularPrice: 45.00,
        imageUrl: 'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&q=80&w=800',
        description: "Set de nutrición orgánica con extractos biológicos de leche y miel. Presentado en caja premium lista para regalar.",
        stock: 100,
        category: 'personal-care',
        tag: 'SET',
        rating: 5,
        reviewCount: 1500,
    }
];
