
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- MAQUILLAJE 2026 ---
    {
        id: 42120,
        name: "Máscara de Pestañas THE ONE 5-in-1 Wonder Lash Ultra 2026",
        brand: "THE ONE",
        price: 8.99,
        regularPrice: 16.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42120%2F42120_1.png',
        description: "LA OBRA MAESTRA DE LA MIRADA. La máscara de pestañas 5 en 1 Wonder Lash Ultra de THE ONE es el estándar de oro para el 2026. Diseñada con nuestra exclusiva tecnología 'Ultra HD', esta fórmula envuelve cada pestaña en un pigmento negro carbón profundo para un impacto visual inmediato. Su cepillo de alta precisión cuenta con un lado de cerdas cortas para depositar la cantidad perfecta de producto y dar volumen desde la raíz, y un lado de cerdas largas que peina, separa y alarga hasta el infinito.\n\nBENEFICIOS COMPROBADOS: 1. VOLUMEN: Hasta un 116% más de densidad en una sola pasada. 2. LONGITUD: Alargamiento extremo gracias a sus polímeros extensores. 3. CURVATURA: Eleva las pestañas sin necesidad de rizador. 4. DEFINICIÓN: Cero grumos, separación pelo a pelo. 5. NUTRICIÓN: Enriquecida con Pro-Vitamina B5 que fortalece la queratina natural de tus pestañas. Es resistente a la humedad y de larga duración (24h), ideal para el ritmo de vida actual, pero se retira fácilmente con agua tibia o limpiador. Una mirada que no solo impacta, sino que también cuida la salud de tus ojos.",
        howToUse: "Aplica en zigzag desde la base hacia las puntas. Usa el lado corto del cepillo para dar volumen y el largo para definir. Reaplica si buscas un efecto más dramático para la noche.",
        stock: 500,
        category: 'makeup',
        tag: 'OFERTA',
        rating: 5,
        reviewCount: 15420,
    },
    {
        id: 42215,
        name: "Base de Maquillaje Antienvejecimiento Giordani Gold 2026",
        brand: "Giordani Gold",
        price: 24.99,
        regularPrice: 38.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42215%2F42215_1.png',
        description: "EL LUJO DE UNA PIEL PERFECTA Y JOVEN. Giordani Gold redefine la elegancia con su base antienvejecimiento más avanzada. No es solo maquillaje, es un tratamiento híbrido que combina color de alta fidelidad con un potente Serum Prebiótico. Diseñada para pieles maduras o aquellas que buscan prevenir los signos de la edad, esta base unifica el tono instantáneamente mientras trabaja en las capas más profundas de la dermis.\n\nTECNOLOGÍA REVOLUCIONARIA: El Serum Prebiótico ayuda a restaurar la barrera cutánea y mejora la hidratación celular. Su textura fluida y sedosa se desliza sobre la piel, difuminando líneas finas, poros y manchas de la edad sin asentarse en las arrugas. Proporciona una cobertura media a alta construible con un acabado luminoso y natural que rejuvenece el rostro al instante. Además, incluye SPF 12 para proteger contra el daño solar diario. Contenida en un frasco de vidrio premium con detalles dorados, esta base es el epítome de la sofisticación para la mujer Oriflame que valora la calidad suprema.",
        stock: 45,
        category: 'makeup',
        tag: 'NOVEDAD',
        rating: 4.9,
        reviewCount: 890,
    },
    {
        id: 38743,
        name: "Barra de Labios OnColour Creamy - Edición 2026",
        brand: "OnColour",
        price: 4.49,
        regularPrice: 9.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38743%2F38743_1.png',
        description: "EXPLOSIÓN DE COLOR Y CONFORT DIARIO. La línea OnColour es la puerta de entrada al color vibrante de Oriflame. Nuestra barra de labios cremosa ha sido formulada para aquellas personas que no quieren renunciar a la hidratación por el color. El 'Cream Comfort Complex' asegura que el labial se deslice como mantequilla, dejando una sensación de suavidad que dura horas.\n\nSu fórmula es rica en pigmentos de alta intensidad, lo que permite una cobertura total desde la primera pasada. Enriquecida con aceites naturales que nutren los labios y evitan que se cuarteen o se sientan secos. El acabado es un satén elegante que aporta jugosidad y volumen visual. Es el labial perfecto para llevar en el bolso y aplicar en cualquier momento del día, ya sea para una reunión de trabajo o una salida casual. Calidad Oriflame al mejor precio, demostrando que la belleza de alta gama puede ser accesible para todos.",
        stock: 300,
        category: 'makeup',
        tag: 'OFERTA',
        rating: 4.7,
        reviewCount: 2100,
    },

    // --- IDEAS PARA REGALAR (MILK & HONEY + MAGNOLIA) ---
    {
        id: 46968,
        name: "Crema de Manos y Cuerpo Milk & Honey Gold 2026",
        brand: "Milk & Honey Gold",
        price: 19.50,
        regularPrice: 28.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46968%2F46968_1.png',
        description: "EL REGALO PERFECTO DE LA NATURALEZA. Milk & Honey Gold es, sin duda, la línea más icónica de Oriflame por una razón: su capacidad inigualable para nutrir y deleitar los sentidos. Esta crema de textura rica y envolvente es una indulgencia pura para la piel. Formulada con extractos de origen biológico de Leche y Miel pura.\n\nPROPIEDADES ÚNICAS: La leche actúa como un acondicionador natural, rico en vitaminas y minerales que suavizan la piel al tacto. La miel es un potente humectante que retiene la hidratación y aporta una luminosidad dorada saludable. Su fragancia característica, cálida y relajante, transforma tu rutina de cuidado corporal en un momento de spa de lujo en casa. Es la idea de regalo número uno, ya que su aroma es amado universalmente y sus beneficios son visibles desde el primer uso. Ideal para todo tipo de pieles, especialmente aquellas que necesitan recuperar su elasticidad y suavidad natural.",
        stock: 200,
        category: 'personal-care',
        tag: 'SET',
        rating: 5,
        reviewCount: 15400,
    },
    {
        id: 31602,
        name: "Exfoliante de Azúcar Milk & Honey Gold Smoothing",
        brand: "Milk & Honey Gold",
        price: 12.99,
        regularPrice: 22.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F31602%2F31602_1.png',
        description: "REVELA UNA PIEL RADIANTE. Este exfoliante de azúcar es el compañero ideal de nuestra crema Milk & Honey. Utiliza partículas de azúcar natural para eliminar suavemente las células muertas de la superficie de la piel, permitiendo que la nutrición posterior penetre mejor. Es un paso esencial para cualquier ritual de belleza corporal.\n\nSu fórmula untuosa contiene extractos de miel para suavizar mientras exfolias, evitando cualquier irritación. La piel queda increíblemente tersa, luminosa y con un aroma dulce y reconfortante que perdura. Es el regalo de autocuidado perfecto para preparar la piel antes de un evento especial o simplemente para disfrutar de un baño relajante. Un clásico de Oriflame que simboliza la pureza y el cuidado artesanal.",
        stock: 150,
        category: 'personal-care',
        tag: 'OFERTA',
        rating: 4.9,
        reviewCount: 8700,
    },
    {
        id: 46802,
        name: "Eau de Toilette Magnolia Enchante 2026",
        brand: "Oriflame Fragrances",
        price: 22.00,
        regularPrice: 35.00,
        imageUrl: 'https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png', // Usamos una imagen de fragancia premium Oriflame
        description: "LA ELEGANCIA HECHA PERFUME. Magnolia Enchante es una oda a la feminidad clásica y la frescura primaveral. Esta fragancia captura la esencia efímera de la flor de magnolia en su punto máximo de floración. Se abre con notas brillantes de Bergamota y Pera, evolucionando hacia un corazón floral opulento donde la Magnolia reina sobre pétalos de Jazmín y Lirio del Valle.\n\nEl fondo es suave y reconfortante, con almizcles blancos y un toque de sándalo que aporta durabilidad y elegancia. Es la fragancia perfecta para regalar a esa persona especial que busca un aroma floral, limpio y distinguido. Su frasco de cristal tallado refleja la luz como un diamante, convirtiéndola en una pieza de decoración preciosa para cualquier tocador. Un aroma que transporta a un jardín en flor bajo el sol de la mañana. Exclusividad Oriflame 2026.",
        stock: 80,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 450,
    }
];
